version: "3.1"

services:
  client:
    build: ./client
    ports:
      - 1234:1234
    environment:
      API_URL: http://server:4444

  server:
    build: ./server
    ports:
      - 4444:4444
    environment:
      DB_URL: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: test

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:

