services:
  server:
    platform: linux/amd64
    build: ./
    ports:
      - "4444:4444"
    environment:
      DB_URL: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: test
      DB_SSL: false
      DB_NAME: postgres

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:

